### ISSUE TITLE
Backend env config

### ISSUE THREAD

**Issue by ErickSaito** [ErickSaito/MC855#1]
**Context**
We need an basic environment to start our development process
 
**Task**
Start the backend configuration with these basic tasks:
- [x] NestJS install
- [x] Docker configure
- [x] Build process configure
- [x] OpenWeatherApi account create
- [x] Install AWS CLI
- [x] Create an account in AWS

**Comment by ErickSaito** [comment]
No comments
