### ISSUE TITLE
Mobile app env config

### ISSUE THREAD

**Issue by ErickSaito** [ErickSaito/MC855#3]
### Context
To develop the React Native app it's necessary to setup the development environment that will be used to develop the app.

### Task
Setup the React Native app initial configurations

- [x] Create app template
- [x] Configure Yarn
- [x] Configure TypeScript
- [x] Have a successfull build on iOS
- [x] Have a succesfull build on Android
